# Generated by Django 4.2 on 2024-01-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_bredd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bredd',
            new_name='Breed',
        ),
    ]
