# Generated by Django 4.2 on 2024-01-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_breed_options_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'порода', 'verbose_name_plural': 'породы'},
        ),
    ]
